# Generated by Django 4.0.4 on 2023-12-31 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('tank_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_unit', models.CharField(choices=[('Lt', 'لیتر'), ('Tn', 'تۆن')], default='Lt', max_length=2)),
                ('buy_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('warning_amount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Lt', 'لیتر'), ('Tn', 'تۆن')], max_length=2)),
                ('to_liter', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('start_work', models.TimeField()),
                ('end_work', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Venders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=50)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.shifts')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.items')),
            ],
        ),
        migrations.CreateModel(
            name='SellByCounters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_unit', models.CharField(choices=[('Lt', 'لیتر'), ('Tn', 'تۆن')], default='Lt', max_length=2)),
                ('buy_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='awat_petrol.items')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_unit', models.CharField(choices=[('Lt', 'لیتر'), ('Tn', 'تۆن')], default='Lt', max_length=2)),
                ('buy_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('lost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clear_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell_date', models.DateField()),
                ('total_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('paid_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('loan_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('last_account', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('note', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('is_counter', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.customers')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='awat_petrol.items')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(max_length=100)),
                ('amount_money', models.PositiveBigIntegerField(default=0)),
                ('return_date', models.DateField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.items')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.shifts')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='buy_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.measures'),
        ),
        migrations.CreateModel(
            name='DailyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('expenses_date', models.DateField()),
                ('note', models.CharField(max_length=100)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.shifts')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.PositiveBigIntegerField(default=0)),
                ('old_register', models.PositiveBigIntegerField(default=0)),
                ('buy_amount', models.PositiveBigIntegerField(default=0)),
                ('buy_amount_money', models.PositiveBigIntegerField(default=0)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.items')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.shifts')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_unit', models.CharField(choices=[('Lt', 'لیتر'), ('Tn', 'تۆن')], default='Lt', max_length=2)),
                ('buy_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('lost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clear_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buy_date', models.DateField()),
                ('total_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('paid_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('loan_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('last_account', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('note', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='awat_petrol.items')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awat_petrol.venders')),
            ],
        ),
    ]
