# Generated by Django 4.0.4 on 2023-11-28 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30, unique=True)),
                ('temporary', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('tank_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_unit', models.CharField(choices=[('Lt', 'لیتر'), ('Tn', 'تۆن')], default='Lt', max_length=2)),
                ('buy_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('warning_amount', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Lt', 'لیتر'), ('Tn', 'تۆن')], max_length=2)),
                ('to_liter', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Venders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('nickname', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshang_petrol.items')),
            ],
        ),
        migrations.CreateModel(
            name='SellShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshang_petrol.items')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshang_petrol.shifts')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_unit', models.CharField(choices=[('Lt', 'لیتر'), ('Tn', 'تۆن')], default='Lt', max_length=2)),
                ('buy_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('lost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clear_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell_date', models.DateField()),
                ('total_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('paid_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('loan_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('last_account', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('note', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshang_petrol.customers')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peshang_petrol.items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='buy_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshang_petrol.measures'),
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_unit', models.CharField(choices=[('Lt', 'لیتر'), ('Tn', 'تۆن')], default='Lt', max_length=2)),
                ('buy_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('lost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clear_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buy_date', models.DateField()),
                ('total_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('paid_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('loan_money', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('last_account', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('note', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peshang_petrol.items')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peshang_petrol.venders')),
            ],
        ),
    ]
