# Generated by Django 4.0.4 on 2023-12-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peshang_petrol', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
